# Generated by Django 5.2.1 on 2025-12-23 17:19

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_batchschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='curriculum_file',
            field=models.FileField(blank=True, help_text='Upload curriculum file (PDF, DOC, PPT, etc. - max 50MB). This will be sent as email attachment.', null=True, upload_to=courses.models.curriculum_file_path, validators=[courses.models.validate_curriculum_file]),
        ),
    ]
